import json
from typing import Dict, List, Any, Optional
from datetime import datetime, timedelta
from dataclasses import dataclass, asdict
from pathlib import Path
from enum import Enum


class GoalOrigin(Enum):
    """Where did this goal come from?"""
    USER_COMMAND = "user"      # User explicitly asked
    PERFORMANCE_GAP = "performance"  # Content underperforming
    OPPORTUNITY = "opportunity" # Detected opportunity (trending topic, etc.)
    RELATIONSHIP = "relationship" # User relationship maintenance
    ONCHAIN = "onchain"         # On-chain opportunity (price movement, etc.)
    REFLECTION = "reflection"   # Self-reflection identified need
    SYSTEM = "system"          # System maintenance


@dataclass
class AutonomousGoal:
    """
    A goal generated by the agent itself
    
    Unlike user-set goals, these have:
    - detected_opportunity: What the agent noticed
    - expected_outcome: What the agent thinks will happen
    - success_criteria: How to know if it worked
    """
    id: str
    description: str
    origin: GoalOrigin
    
    # What triggered this goal
    detected_opportunity: str
    evidence: Dict[str, Any]  # Data that led to this conclusion
    
    # Execution
    action_plan: List[str]  # Steps to take
    expected_outcome: str
    success_criteria: List[str]
    
    # Priority (0-10, higher = more important)
    priority_score: float = 5.0
    urgency: float = 5.0  # Time sensitivity
    impact: float = 5.0   # Potential benefit
    
    # Execution state
    current_step: int = 0
    
    # Status
    status: str = 'proposed'  # proposed, approved, active, completed, failed
    created_at: datetime = None
    activated_at: datetime = None
    completed_at: datetime = None
    
    # Results
    actual_outcome: str = None
    outcome_rating: float = 0.0  # -1 to 1
    
    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.now()
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'description': self.description,
            'origin': self.origin.value,
            'detected_opportunity': self.detected_opportunity,
            'evidence': self.evidence,
            'action_plan': self.action_plan,
            'current_step': self.current_step,
            'expected_outcome': self.expected_outcome,
            'success_criteria': self.success_criteria,
            'priority_score': self.priority_score,
            'urgency': self.urgency,
            'impact': self.impact,
            'status': self.status,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'activated_at': self.activated_at.isoformat() if self.activated_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'actual_outcome': self.actual_outcome,
            'outcome_rating': self.outcome_rating
        }


class OpportunityDetector:
    """
    Analyzes data to find opportunities for the agent to act
    """
    
    def __init__(self, unified_memory=None, phase12_learning=None):
        self.memory = unified_memory
        self.phase12 = phase12_learning
    
    def detect_content_opportunities(self) -> List[Dict]:
        """
        Find content opportunities based on performance data
        
        Returns opportunities like:
        - "Topic X is trending but we haven't posted about it"
        - "Our posts about Y get 3x engagement, should post more"
        """
        opportunities = []
        
        if not self.phase12:
            return opportunities
        
        # 1. Check for high-performing topics we haven't covered recently
        top_topics = self.phase12.get_top_topics(limit=5, days=7)
        for topic_data in top_topics:
            topic = topic_data['topic']
            avg_engagement = topic_data.get('avg_engagement', 0)
            
            # If engagement is high, suggest more content
            if avg_engagement > 50:  # Threshold
                opportunities.append({
                    'type': 'content_gap',
                    'description': f"High engagement on '{topic}' ({avg_engagement:.1f} avg)",
                    'suggested_action': f"Create post about {topic}",
                    'expected_impact': avg_engagement * 1.2,
                    'urgency': 7
                })
        
        # 2. Check for rising topics (increasing engagement)
        trends = self.phase12.get_topic_trends(weeks=2)
        for week_key, week_data in trends.items():
            for item in week_data:
                topic = item.get('topic')
                engagement = item.get('avg_engagement', 0)
                if engagement > 30 and week_key == 'week_1':  # Recent week
                    opportunities.append({
                        'type': 'rising_topic',
                        'description': f"'{topic}' is trending up",
                        'suggested_action': f"Engage with {topic} content",
                        'expected_impact': engagement,
                        'urgency': 8
                    })
        
        return opportunities
    
    def detect_relationship_opportunities(self) -> List[Dict]:
        """
        Find opportunities to strengthen user relationships
        """
        opportunities = []
        
        if not self.phase12:
            return opportunities
        
        # Get active users we haven't interacted with recently
        active_users = self.phase12.get_active_community_members(days=7)
        
        for user in active_users:
            interaction_count = user.get('interaction_count', 0)
            last_interaction = user.get('last_interaction', '')
            
            # High-value users who need attention
            if interaction_count > 5:
                # Check if it's been a while
                try:
                    last_dt = datetime.fromisoformat(last_interaction.replace('Z', '+00:00'))
                    days_since = (datetime.now() - last_dt).days
                    
                    if days_since > 3:
                        opportunities.append({
                            'type': 'relationship_maintenance',
                            'description': f"User {user.get('username')} hasn't been engaged in {days_since} days",
                            'suggested_action': f"Reply to their content or send appreciation",
                            'expected_impact': interaction_count * 2,
                            'urgency': 6,
                            'target_user': user.get('user_id')
                        })
                except:
                    pass
        
        return opportunities
    
    def detect_onchain_opportunities(self, onchain_plugin=None) -> List[Dict]:
        """
        Find on-chain opportunities
        """
        opportunities = []
        
        if not onchain_plugin or not hasattr(onchain_plugin, 'web3_provider'):
            return opportunities
        
        # Check for significant balance changes
        if hasattr(onchain_plugin, 'token_snapshots') and onchain_plugin.token_snapshots:
            changes = onchain_plugin.check_balance_changes()
            if changes:
                for symbol, change_data in changes.items():
                    if change_data['change'] > 0:
                        opportunities.append({
                            'type': 'onchain_received',
                            'description': f"Received {change_data['change']:.4f} {symbol}",
                            'suggested_action': "Thank sender, acknowledge support",
                            'expected_impact': 10,
                            'urgency': 9
                        })
        
        return opportunities


class GoalGenerator:
    """
    Converts detected opportunities into concrete goals
    """
    
    def __init__(self, opportunity_detector: OpportunityDetector):
        self.detector = opportunity_detector
    
    def generate_goals(self, onchain_plugin=None) -> List[AutonomousGoal]:
        """
        Generate goals from all opportunity sources
        """
        goals = []
        
        # 1. Content opportunities
        content_ops = self.detector.detect_content_opportunities()
        for opp in content_ops:
            goal = self._create_goal_from_opportunity(opp, GoalOrigin.OPPORTUNITY)
            if goal:
                goals.append(goal)
        
        # 2. Relationship opportunities
        rel_ops = self.detector.detect_relationship_opportunities()
        for opp in rel_ops:
            goal = self._create_goal_from_opportunity(opp, GoalOrigin.RELATIONSHIP)
            if goal:
                goals.append(goal)
        
        # 3. On-chain opportunities
        if onchain_plugin:
            chain_ops = self.detector.detect_onchain_opportunities(onchain_plugin)
            for opp in chain_ops:
                goal = self._create_goal_from_opportunity(opp, GoalOrigin.ONCHAIN)
                if goal:
                    goals.append(goal)
        
        # Sort by priority score
        goals.sort(key=lambda g: g.priority_score, reverse=True)
        return goals
    
    def _create_goal_from_opportunity(self, opp: Dict, origin: GoalOrigin) -> Optional[AutonomousGoal]:
        """
        Convert opportunity dict to AutonomousGoal
        """
        
        goal_id = f"goal_auto_{datetime.now().timestamp()}"
        
        # Build action plan based on type
        action_plan = [opp['suggested_action']]
        if opp['type'] == 'content_gap':
            action_plan.extend([
                "Generate content using AI",
                "Post to appropriate platform",
                "Track engagement"
            ])
        elif opp['type'] == 'relationship_maintenance':
            action_plan.extend([
                "Find user's recent content",
                "Craft personalized reply",
                "Send reply"
            ])
        elif opp['type'] == 'onchain_received':
            action_plan.extend([
                "Identify sender",
                "Send thank you message",
                "Record transaction in ledger"
            ])
        
        return AutonomousGoal(
            id=goal_id,
            description=f"Autonomously generated goal: {opp['description']}",
            origin=origin,
            detected_opportunity=opp['description'],
            evidence=opp,
            action_plan=action_plan,
            expected_outcome=opp['expected_impact'],
            success_criteria=["Action executed", "Expected impact achieved"],
            priority_score=opp.get('urgency', 5.0) + opp.get('expected_impact', 0) / 10
        )


class AutonomousGoalManager:
    """
    Manages the lifecycle of autonomous goals
    """
    
    def __init__(self, unified_memory=None, phase12_learning=None, onchain_plugin=None, storage_path: str = "data/autonomous_goals.json"):
        self.unified_memory = unified_memory
        self.phase12_learning = phase12_learning
        self.onchain_plugin = onchain_plugin
        self.storage_path = Path(storage_path)
        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        self.goals: List[AutonomousGoal] = []
        self.goal_generator = OpportunityDetector(unified_memory, phase12_learning)
        self._load()
        
    def scan_and_generate(self, onchain_plugin=None) -> List[AutonomousGoal]:
        """
        Scan for opportunities and generate new goals
        """
        new_goals = self.goal_generator.generate_goals(onchain_plugin)
        for goal in new_goals:
            # Avoid duplicates for now (simple check)
            if not any(g.description == goal.description for g in self.goals):
                self.goals.append(goal)
                self.unified_memory.store(
                    content=f"New autonomous goal generated: {goal.description}",
                    memory_type=\'goal\',
                    metadata=goal.to_dict()
                )
        self.goals.sort(key=lambda g: g.priority_score, reverse=True)
        self._save()
        return new_goals
    
    def get_active_goals(self) -> List[AutonomousGoal]:
        """
        Get goals that are proposed or active
        """
        return [g for g in self.goals if g.status in ['proposed', 'approved', 'active']]
    
    def get_proposed_goals(self) -> List[AutonomousGoal]:
        """
        Get goals that are proposed but not yet approved/active
        """
        return [g for g in self.goals if g.status == 'proposed']
    
    def approve_goal(self, goal_id: str) -> Optional[AutonomousGoal]:
        """
        Approve a proposed goal, making it active
        """
        for goal in self.goals:
            if goal.id == goal_id and goal.status == 'proposed':
                goal.status = 'active'
                goal.activated_at = datetime.now()
                self.unified_memory.store(
                    content=f"Autonomous goal approved and activated: {goal.description}",
                    memory_type=\'goal_status_change\',
                    metadata=goal.to_dict()
                )
                self._save()
                return goal
        return None
    
    def get_next_action(self) -> Optional[Dict]:
        """
        Get the next action for the highest priority active goal
        """
        active_goals = self.get_active_goals()
        if not active_goals:
            return None
        
        # For simplicity, just take the first step of the highest priority active goal
        highest_priority_goal = active_goals[0]
        if highest_priority_goal.current_step < len(highest_priority_goal.action_plan):
            action = highest_priority_goal.action_plan[highest_priority_goal.current_step]
            return {
                'goal_id': highest_priority_goal.id,
                'goal_description': highest_priority_goal.description,
                'action': action,
                'step': highest_priority_goal.current_step
            }
        return None
    
    def complete_action(self, goal_id: str, success: bool, outcome: str) -> Optional[AutonomousGoal]:
        """
        Mark the current action of a goal as complete
        """
        for goal in self.goals:
            if goal.id == goal_id and goal.status == 'active':
                if success:
                    goal.current_step += 1
                    if goal.current_step >= len(goal.action_plan):
                        goal.status = 'completed'
                        goal.completed_at = datetime.now()
                        goal.actual_outcome = outcome
                        goal.outcome_rating = 1.0
                        self.unified_memory.store(
                            content=f"Autonomous goal completed: {goal.description}",
                            memory_type=\'goal_status_change\',
                            metadata=goal.to_dict()
                        )
                    else:
                        self.unified_memory.store(
                            content=f"Autonomous goal {goal.id} step {goal.current_step-1} completed. Next step: {goal.action_plan[goal.current_step]}",
                            memory_type=\'goal_progress\',
                            metadata=goal.to_dict()
                        )
                else:
                    goal.status = 'failed'
                    goal.completed_at = datetime.now()
                    goal.actual_outcome = outcome
                    goal.outcome_rating = -1.0
                    self.unified_memory.store(
                        content=f"Autonomous goal failed: {goal.description}. Outcome: {outcome}",
                        memory_type=\'goal_status_change\',
                        metadata=goal.to_dict()
                    )
                self._save()
                return goal
        return None
    
    def _save(self):
        """
        Persist goals to disk
        """
        try:
            data = [g.to_dict() for g in self.goals]
            with open(self.storage_path, "w") as f:
                json.dump(data, f, indent=2)
        except Exception as e:
            print(f"⚠️ Failed to save autonomous goals: {e}")
    
    def _load(self):
        """
        Load goals from disk
        """
        try:
            if self.storage_path.exists():
                with open(self.storage_path, "r") as f:
                    data = json.load(f)
                self.goals = [AutonomousGoal(**g) for g in data]
                print(f"✅ Loaded {len(self.goals)} autonomous goals")
        except Exception as e:
            print(f"⚠️ Failed to load autonomous goals: {e}")

def create_autonomous_goal_manager(unified_memory=None, phase12_learning=None, onchain_plugin=None) -> AutonomousGoalManager:
    """
    Factory function to create an AutonomousGoalManager
    """
    return AutonomousGoalManager(
        unified_memory=unified_memory,
        phase12_learning=phase12_learning,
        onchain_plugin=onchain_plugin,
        storage_path="/Users/ton/aura_creatine_agents/data/autonomous_goals.json"
    )
